##
# This file is part of RGPD project.
#
# (c) SÃ©bastien CHOMY <sebastien.chomy@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##
framework:
    validation: { enable_annotations: true }
